@we @1.0 @ew
Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "female"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Married"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "male"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Engaged"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "male"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Single"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "male"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Married"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "female"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Single"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "female"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Engaged"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "male"
And I select from dropdown "[Birth_month]" the value "valid"
And I select from dropdown "[Birth_day]" the value "invalid"
And I select from dropdown "[Relationship_Status]" the value "Single"

Given I navigate to "https://www.tiffany.com"
And I mouse hover on "[MyAccount]"
And I click on "[Create account]" link
And I add wait seconds of "30"
And I enter into input field "[FirstName]" the value "Jane"
And I enter into input field "[LastName]" the value "Chen"
And I enter into input field "[Email]" the value "whcjing@cn.ibm.com"
And I select radio "[Gender]" with the option "female"
And I select from dropdown "[Birth_month]" the value "invalid"
And I select from dropdown "[Birth_day]" the value "valid"
And I select from dropdown "[Relationship_Status]" the value "Engaged"

